// export const sample_foods = [
//   {
//     id: '1',
//     name: 'briyani',
//     cookTime: '20-30',
//     price: 100,
//     favorite: false,
//     origins: ['india'],
//     stars: 4.5,
//     imageUrl: '\public\briyani.jpg',
//     tags: ['FastFood', 'briyani', 'Lunch'],
//   },
//   {
//     id: '2',
//     name: 'ButterChicken',
//     price: 200,
//     cookTime: '20-30',
//     favorite: true,
//     origins: ['southAfrica', 'middle east', 'India'],
//     stars: 5,
//     imageUrl: '\public\butterchicken.jpg',
//     tags: ['SlowFood', 'Lunch', 'sides'],
//   },
//   {
//     id: '3',
//     name: 'dosai',
//     price: 10,
//     cookTime: '10-15',
//     favorite: false,
//     origins: ['india', 'us'],
//     stars: 3.5,
//     imageUrl: '\public\dosai.jpg',
//     tags: ['FastFood', 'dosai', 'Lunch'],
//   },
//   {
//     id: '4',
//     name: 'Naan',
//     price: 2,
//     cookTime: '15-20',
//     favorite: true,
//     origins: ['india', 'middle east'],
//     stars: 3,
//     imageUrl: '\public\naan.jpg',
//     tags: ['sides', 'Fry','Lunch'],
//   },
//   {
//     id: '5',
//     name: 'Non-veg meals',
//     price: 120,
//     cookTime: '40-50',
//     favorite: false,
//     origins: ['india', 'asia'],
//     stars: 3.5,
//     imageUrl: '\public\nonvegthali.jpg',
//     tags: ['SlowFood', 'lunch','Soup'],
//   },
//   {
//     id: '6',
//     name: 'Veg Thali',
//     price: 90,
//     cookTime: '40-50',
//     favorite: false,
//     origins: ['india', 'asia'],
//     stars: 4.0,
//     imageUrl: '\public\vegthali.jpg',
//     tags: ['FastFood', 'veg', 'Lunch'],
//   },
// ];

// export const sample_tags = [
//   { name: 'All', count: 6 },
//   { name: 'FastFood', count: 4 },
//   { name: 'briyani', count: 2 },
//   { name: 'Lunch', count: 3 },
//   { name: 'SlowFood', count: 2 },
//   { name: 'veg', count: 1 },
//   { name: 'sides', count: 2 },
//   { name: 'Soup', count: 1 },
// ];
export const sample_foods = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'india-tamilnadu',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'steven',
    email: 'steven@gmail.com',
    password: '12345',
    address: 'usa-newyork',
    isAdmin: true,
  },
];
