// export const sample_foods = [
//   {
//     id: '1',
//     name: 'Pizza Pepperoni',
//     cookTime: '10-20',
//     price: 10,
//     favorite: false,
//     origins: ['italy'],
//     stars: 4.5,
//     imageUrl: 'food-1.jpg',
//     tags: ['FastFood', 'Pizza', 'Lunch'],
//   },
//   {
//     id: '2',
//     name: 'Meatball',
//     price: 20,
//     cookTime: '20-30',
//     favorite: true,
//     origins: ['persia', 'middle east', 'china'],
//     stars: 5,
//     imageUrl: 'food-2.jpg',
//     tags: ['SlowFood', 'Lunch'],
//   },
//   {
//     id: '3',
//     name: 'Hamburger',
//     price: 5,
//     cookTime: '10-15',
//     favorite: false,
//     origins: ['germany', 'us'],
//     stars: 3.5,
//     imageUrl: 'food-3.jpg',
//     tags: ['FastFood', 'Hamburger'],
//   },
//   {
//     id: '4',
//     name: 'Fried Potatoes',
//     price: 2,
//     cookTime: '15-20',
//     favorite: true,
//     origins: ['belgium', 'france'],
//     stars: 3,
//     imageUrl: 'food-4.jpg',
//     tags: ['FastFood', 'Fry'],
//   },
//   {
//     id: '5',
//     name: 'Chicken Soup',
//     price: 11,
//     cookTime: '40-50',
//     favorite: false,
//     origins: ['india', 'asia'],
//     stars: 3.5,
//     imageUrl: 'food-5.jpg',
//     tags: ['SlowFood', 'Soup'],
//   },
//   {
//     id: '6',
//     name: 'Vegetables Pizza',
//     price: 9,
//     cookTime: '40-50',
//     favorite: false,
//     origins: ['italy'],
//     stars: 4.0,
//     imageUrl: 'food-6.jpg',
//     tags: ['FastFood', 'Pizza', 'Lunch'],
//   },
// ];
export const sample_foods = [
  {
    id: '1',
    name: 'Chicken Briyani',
    cookTime: '30-40',
    price: 120,
    favorite: false,
    origins: ['india', 'asia'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['Briyani', 'Pizza', 'Lunch','Non-Veg'],
  },
  {
    id: '2',
    name: 'Dosai',
    price: 20,
    cookTime: '05-10',
    favorite: true,
    origins: ['inida', 'middle east', 'china'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['SlowFood', 'Breakfast', 'Dinner','Veg'],
  },
  {
    id: '3',
    name: 'Butter Chicken',
    price: 200,
    cookTime: '20-30',
    favorite: false,
    origins: ['india', 'us', 'asia'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['Non-Veg','FastFood', 'Grilled', 'Lunch', 'Dinner'],
  },
  {
    id: '4',
    name: 'Veg Salad',
    price: 60,
    cookTime: '10-20',
    favorite: true,
    origins: ['italy', 'france','india'],
    stars: 3,
    imageUrl: 'food-4.jpg',
    tags: ['SlowFood', 'Lunch', 'Dinner', 'Salad', 'Veg', 'Breakfast'],
  },
  {
    id: '5',
    name: 'Mushroom Gravy',
    price: 110,
    cookTime: '20-30',
    favorite: false,
    origins: ['india', 'asia',],
    stars: 3.5,
    imageUrl: 'food-5.jpg',
    tags: ['SlowFood', 'Sides','Veg'],
  },
  {
    id: '6',
    name: 'Pizza Pepperoni',
    price: 220,
    cookTime: '10-20',
    favorite: false,
    origins: ['italy', 'france'],
    stars: 4.0,
    imageUrl: 'food-6.jpg',
    tags: ['Non-Veg','FastFood', 'Pizza', 'Lunch'],
  },
  
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 2 },
  { name: 'Pizza', count: 1 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 3 },
  { name: 'Veg', count: 3 },
  { name: 'Non-Veg', count: 3 },
  { name: 'Sides', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'india-tamilnadu',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'steven',
    email: 'steven@gmail.com',
    password: '12345',
    address: 'usa-newyork',
    isAdmin: true,
  },
];
