// export const sample_foods = [
//   {
//     id: '1',
//     name: 'Pizza Pepperoni',
//     cookTime: '10-20',
//     price: 180,
//     favorite: false,
//     origins: ['italy'],
//     stars: 4.5,
//     imageUrl: 'food-1.jpg',
//     tags: ['FastFood', 'Pizza', 'Lunch'],
//   },
//   {
//     id: '2',
//     name: 'Meatball',
//     price: 200,
//     cookTime: '20-30',
//     favorite: true,
//     origins: ['persia', 'middle east', 'china'],
//     stars: 5,
//     imageUrl: 'food-2.jpg',
//     tags: ['SlowFood', 'Lunch'],
//   },
//   {
//     id: '3',
//     name: 'Hamburger',
//     price: 150,
//     cookTime: '10-15',
//     favorite: false,
//     origins: ['germany', 'us'],
//     stars: 3.5,
//     imageUrl: 'food-3.jpg',
//     tags: ['FastFood', 'Hamburger'],
//   },
//   {
//     id: '4',
//     name: 'Fried Potatoes',
//     price: 50,
//     cookTime: '15-20',
//     favorite: true,
//     origins: ['belgium', 'france'],
//     stars: 3,
//     imageUrl: 'food-4.jpg',
//     tags: ['FastFood', 'Fry'],
//   },
//   {
//     id: '5',
//     name: 'Chicken Soup',
//     price: 40,
//     cookTime: '40-50',
//     favorite: false,
//     origins: ['india', 'asia'],
//     stars: 3.5,
//     imageUrl: 'food-5.jpg',
//     tags: ['SlowFood', 'Soup'],
//   },
//   {
//     id: '6',
//     name: 'Vegetables Pizza',
//     price: 120,
//     cookTime: '40-50',
//     favorite: false,
//     origins: ['italy'],
//     stars: 4.0,
//     imageUrl: 'food-6.jpg',
//     tags: ['FastFood', 'Pizza', 'Lunch'],
//   },
// ];

// export const sample_tags = [
//   { name: 'All', count: 6 },
//   { name: 'FastFood', count: 4 },
//   { name: 'Pizza', count: 2 },
//   { name: 'Lunch', count: 3 },
//   { name: 'SlowFood', count: 2 },
//   { name: 'Hamburger', count: 1 },
//   { name: 'Fry', count: 1 },
//   { name: 'Soup', count: 1 },
// ];

export const sample_foods = [
  {
    id: '1',
    name: 'Briyani',
    cookTime: '30-45',
    price: 250,
    favorite: true,
    origins: ['india'],
    stars: 4.8,
    imageUrl: 'briyani.jpg',
    tags: ['Lunch', 'Dinner', 'Non-Veg'],
  },
  {
    id: '2',
    name: 'Butter Chicken',
    price: 300,
    cookTime: '40-50',
    favorite: true,
    origins: ['india'],
    stars: 5,
    imageUrl: 'butter-chicken.jpg',
    tags: ['Lunch', 'Dinner', 'Non-Veg'],
  },
  {
    id: '3',
    name: 'Dosai',
    price: 100,
    cookTime: '15-20',
    favorite: true,
    origins: ['india'],
    stars: 4.5,
    imageUrl: 'dosai.jpg',
    tags: ['Breakfast', 'Dinner', 'Veg'],
  },
  {
    id: '4',
    name: 'Veg Salad',
    price: 80,
    cookTime: '10-15',
    favorite: false,
    origins: ['global'],
    stars: 4.0,
    imageUrl: 'veg-salad.jpg',
    tags: ['Breakfast', 'Lunch', 'Dinner', 'Veg'],
  },
  {
    id: '5',
    name: 'Mushroom Gravy',
    price: 150,
    cookTime: '30-40',
    favorite: false,
    origins: ['india'],
    stars: 4.3,
    imageUrl: 'mushroom-gravy.jpg',
    tags: ['Lunch', 'Dinner', 'Veg'],
  },
  {
    id: '6',
    name: 'Pizza',
    price: 200,
    cookTime: '20-30',
    favorite: true,
    origins: ['italy'],
    stars: 4.7,
    imageUrl: 'pizza.jpg',
    tags: ['Lunch', 'Dinner', 'FastFood', 'Pizza'],
  },
];
export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'Lunch', count: 5 },
  { name: 'Dinner', count: 5 },
  { name: 'Breakfast', count: 2 },
  { name: 'Veg', count: 3 },
  { name: 'Non-Veg', count: 2 },
  { name: 'FastFood', count: 1 },
  { name: 'Pizza', count: 1 },
];


export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'india-tamilnadu',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'steven',
    email: 'steven@gmail.com',
    password: '12345',
    address: 'usa-newyork',
    isAdmin: true,
  },
];
